config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Commontator::Engine => '/vox-populi'
  
  resources :citizens, except: [:index]
  
  resources :projects, except: [:index, :show]
  resources :project_members, only: [:create, :destroy]
  resources :facilities, except: [:index]
  resources :loans, except: [:index, :edit, :update, :show]
  resources :bonds, except: [:index, :edit, :update, :show]
  
  resources :districts, only: [:index, :show]

  resources :equipment_types, only: [:index, :show]
  
  resources :facility_types, only: [:index, :show]
  
  resources :professions, only: [:index, :show]
  
  resources :skills, only: [:index, :show]
  
  resources :trade_goods, only: [:index, :show]
  
  resources :help_topics, only: [:index, :show]
  
  resources :events, only: [:show]

  resources :exchange_equipments, only: [:new, :create]
  resources :exchange_trade_goods, only: [:new, :create]
  
  resources :petitions do 
    member do 
      post :vote_for
      post :vote_against
    end
  end

  resources :stories, only: [:index]
  resources :story_nodes, only: [:show, :edit, :update] do 
    member do 
      get :flag, as: :flag
      get :unflag, as: :unflag
    end
  end
  resources :story_choices, only: [:show, :create]
  
  devise_for :users

  get 'charts/total_land', to: 'district_charts#total_land'
  get 'charts/free_land', to: 'district_charts#free_land'
  get 'charts/transport_capacity', to: 'district_charts#transport_capacity'
  get 'charts/civilians', to: 'district_charts#civilians'
  get 'charts/automatons', to: 'district_charts#automatons'
  get 'charts/unrest', to: 'district_charts#unrest'
  get 'charts/health', to: 'district_charts#health'
  get 'charts/policing', to: 'district_charts#policing'
  get 'charts/social', to: 'district_charts#social'
  get 'charts/environment', to: 'district_charts#environment'
  get 'charts/housing', to: 'district_charts#housing'
  get 'charts/education', to: 'district_charts#education'
  get 'charts/community', to: 'district_charts#community'
  get 'charts/creativity', to: 'district_charts#creativity'
  get 'charts/aesthetics', to: 'district_charts#aesthetics'
  get 'charts/crime', to: 'district_charts#crime'
  get 'charts/corruption', to: 'district_charts#corruption'
  get 'charts/infrastructure', to: 'global_charts#infrastructure'
  get 'charts/grid', to: 'global_charts#grid'
  get 'charts/power', to: 'global_charts#power'
  get 'charts/stability', to: 'global_charts#stability'
  get 'charts/climate', to: 'global_charts#climate'
  get 'charts/liberty', to: 'global_charts#liberty'
  get 'charts/security', to: 'global_charts#security'
  get 'charts/borders', to: 'global_charts#borders'
  get 'charts/inflation', to: 'global_charts#inflation'
  get 'charts/citizens', to: 'global_charts#citizens'
  get 'charts/gdp', to: 'global_charts#gdp'
  get 'charts', to: 'global_charts#index'

  root 'welcome#index'

  get 'test_exception_notifier', :controller => 'application', :action => 'test_exception_notifier'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/views/welcome/index.html.erb
<% content_for :title, "Ultimapolis" %>
<% 
unless current_user && !current_user.admin? && current_user.citizen
	button_html = [link_to("Become a Citizen", new_citizen_path, class: "btn-lg btn-primary")]
else 
	button_html = [
		link_to("Tell your Story", stories_path, class: "btn-lg btn-primary"),
		link_to("Join a Project", current_citizen_path('projects'), class: "btn-lg btn-info"),
		link_to("Manage Facilities", current_citizen_path('facilities'), class: "btn-lg btn-primary"),
		link_to("View Profile", current_citizen_path('profile'), class: "btn-lg btn-info")
	]
end %>
<% content_for :lead, "The future city simulation.<p>#{button_html.join('&nbsp;&nbsp;&nbsp;').html_safe}</p>".html_safe %>
<% cache(cache_key_for_name("welcome")) do %>
	<div class="row">
		<div class="col-lg-5">
			<div class="panel panel-primary">
			  <div class="panel-heading">
			    <h3 class="panel-title">Current Opportunity</h3>
			  </div>
			  <div class="panel-body">
			  	<% if Event.current_opportunity %>
			  	<%=render partial: '/events/briefing', locals: {event: Event.current_opportunity} %>
			  	<% else %>
			  	<p>There is no current opportunity. There will be another along shortly.</p>
			  	<% end %>
			  </div>
			</div>
		</div>
		<div class="col-lg-2">
			<%
			panel_class = if Global.singleton.notes.empty?
				"panel-success"
			else
				"panel-warning"
			end
			%>
			<div class="panel <%=panel_class%>">
			  <div class="panel-heading">
			    <h3 class="panel-title">City Status</h3>
			  </div>
			  <div class="panel-body">
		    	<% if Global.singleton.notes.empty? %>
		    	<p>
	        		Peace and prosperity
	        	</p>
	        	<% elsif Global.singleton.notes.count == 1 %>
	        	<p><%=Global.singleton.notes[0]%></p> 
	        	<% else %>
	        	<ul class="list-group">
	        		<% Global.singleton.notes.each do |note| %>
	        		<li class="list-group-item">
	        			<%=note.html_safe %>
	        		</li>
	        		<% end %>
	        	</ul>
	        	<% end %>
	        	<p>
	        		<strong>GDP:</strong> <%=link_to(format_currency(Global.singleton.gdp), '/charts?chart=gdp') %>
	        	</p>
	        	<p>
	        		<strong>Inflation:</strong> <%=link_to(format_rating(Global.singleton.inflation), '/charts?chart=inflation')%>
	        	</p>
	        	<p>
	        		<strong>Interest Rate:</strong> <%=link_to(format_rating(Global.singleton.interest), '/charts?chart=interest')%>
	        	</p>
			  </div>
			</div>
		</div>
		<div class="col-lg-5">
			<div class="panel panel-danger">
			  <div class="panel-heading">
			    <h3 class="panel-title">Current Crisis</h3>
			  </div>
			  <div class="panel-body">
			    <% if Event.current_crisis %>
			    <%=render partial: '/events/briefing', locals: {event: Event.current_crisis} %>
			  	<% else %>
			  	<p>There is no current crisis. Phew!</p>
			  	<% end %>
			  </div>
			</div>
		</div>
	</div>
	<% reports = TurnReport.global_news.limit(5) %>
	<% unless reports.empty? %>
	<h2>News Headlines</h2>
	<ul class="list-group">
	  <% reports.each do |report| %>
	  <li class="list-group-item">
	    <%=link_to("#{report.district}: #{report.to_s}".html_safe, report.district)%>
	    <span class="badge"><%=format_turn(report.turn)%></span>
	  </li>
	  <% end %>
	</ul>
	<% end%>
<% end %>
<% content_for :help_title, "What is this?" %>
<% content_for :help_body do %>
Ultimapolis is a persistent browser-based game which sumulates the workings of a single futuristic city. Citizens run by players compete and collaborate to deal with new crisis and opportunities whilst expanding their own pool of knowledge (skills) and resources. The simulation is the foundation for a roleplaying game. There is no final objective to achieve and different citizens will have different ideas about what is the best for their city.
<% end %>