config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Commontator::Engine => '/vox-populi'
  
  resources :citizens, except: [:index]
  
  resources :projects, except: [:index, :show]
  resources :project_members, only: [:create, :destroy]
  resources :facilities, except: [:index]
  resources :loans, except: [:index, :edit, :update, :show]
  resources :bonds, except: [:index, :edit, :update, :show]
  
  resources :districts, only: [:index, :show]

  resources :equipment_types, only: [:index, :show]
  
  resources :facility_types, only: [:index, :show]
  
  resources :professions, only: [:index, :show]
  
  resources :skills, only: [:index, :show]
  
  resources :trade_goods, only: [:index, :show]
  
  resources :help_topics, only: [:index, :show]
  
  resources :events, only: [:show]

  resources :exchange_equipments, only: [:new, :create]
  resources :exchange_trade_goods, only: [:new, :create]
  
  resources :petitions do 
    member do 
      post :vote_for
      post :vote_against
    end
  end

  resources :stories, only: [:index]
  resources :story_nodes, only: [:show, :edit, :update] do 
    member do 
      get :flag, as: :flag
      get :unflag, as: :unflag
    end
  end
  resources :story_choices, only: [:show, :create]
  
  devise_for :users

  get 'charts/total_land', to: 'district_charts#total_land'
  get 'charts/free_land', to: 'district_charts#free_land'
  get 'charts/transport_capacity', to: 'district_charts#transport_capacity'
  get 'charts/civilians', to: 'district_charts#civilians'
  get 'charts/automatons', to: 'district_charts#automatons'
  get 'charts/unrest', to: 'district_charts#unrest'
  get 'charts/health', to: 'district_charts#health'
  get 'charts/policing', to: 'district_charts#policing'
  get 'charts/social', to: 'district_charts#social'
  get 'charts/environment', to: 'district_charts#environment'
  get 'charts/housing', to: 'district_charts#housing'
  get 'charts/education', to: 'district_charts#education'
  get 'charts/community', to: 'district_charts#community'
  get 'charts/creativity', to: 'district_charts#creativity'
  get 'charts/aesthetics', to: 'district_charts#aesthetics'
  get 'charts/crime', to: 'district_charts#crime'
  get 'charts/corruption', to: 'district_charts#corruption'
  get 'charts/infrastructure', to: 'global_charts#infrastructure'
  get 'charts/grid', to: 'global_charts#grid'
  get 'charts/power', to: 'global_charts#power'
  get 'charts/stability', to: 'global_charts#stability'
  get 'charts/climate', to: 'global_charts#climate'
  get 'charts/liberty', to: 'global_charts#liberty'
  get 'charts/security', to: 'global_charts#security'
  get 'charts/borders', to: 'global_charts#borders'
  get 'charts/inflation', to: 'global_charts#inflation'
  get 'charts/citizens', to: 'global_charts#citizens'
  get 'charts/gdp', to: 'global_charts#gdp'
  get 'charts', to: 'global_charts#index'

  root 'welcome#index'

  get 'test_exception_notifier', :controller => 'application', :action => 'test_exception_notifier'
end

app/models/concerns/event_types.rb
module EventTypes
	require 'csv'
	extend ActiveSupport::Concern

	SPECIAL_MODIFIERS = {
		'transport_capacity' => 1000
	}

	def self.template_file_path
		File.expand_path('../../../../config/event_templates.csv', __FILE__)
	end

	def self.crisis_templates
		@@crisis_templates ||= event_templates && event_templates.select{|template| template['Type'] == 'Crisis'}
	end

	def self.opportunity_templates
		@@opportunity_templates ||= event_templates && event_templates.select{|template| template['Type'] == 'Opportunity'}
	end

	def self.generate_crisis!
		triggered = false
		sanity = 10
		while !triggered && sanity > 0 do
			district = District.all.to_a.sample
			crisis_templates.each do |template|
				if event_triggable?(template, district)
					triggered = true
					create_event!(district, template)
					break
				end
			end
			sanity -= 1
		end
		raise "Could not generate crisis" unless triggered
	end

	def self.test_event_templates!
		district = District.first
		event_templates.each do |template|
			create_event!(district, template)
		end
	end

	def self.generate_opportunity!
		district = District.all.to_a.sample
		create_event!(district, opportunity_templates.sample)
	end

	def self.event_templates
		return unless File.exist?(template_file_path)
		@@event_templates ||= CSV.read(template_file_path, headers: true)
	end

	def self.event_triggable?(template, district)
		return false unless district
		return true if template['Trigger'].blank?
		district.send(template['Trigger'].to_sym)
	end

	def self.create_event!(district, template)
		event = Event.create!(
			name: "#{district}: #{template['Name']}",
			event_type: template['Type'],
			started_on: Global.singleton.turn,
			max_duration: 24,
			summary: template['Summary'].gsub('district',district.to_s),
			description: template['Description'].gsub('district',district.to_s),
			icon: "/icons/#{template['Type'].downcase}/#{template['Name'].gsub(' ', '_').downcase}.png"
		)
		
		unless template['District Effect +'].blank?
			effect_field = template['District Effect +'].strip.to_sym
			event.add_district_effect!(district, effect_field, field_modifier(template['District Effect +']))
		end
		unless template['District Effect -'].blank?
			effect_field = template['District Effect -'].strip.to_sym
			event.add_district_effect!(district, effect_field, (0 - field_modifier(template['District Effect -'])))
		end
		unless template['Global Effect +'].blank?
			effect_field = template['Global Effect +'].strip.to_sym
			event.add_global_effect!(effect_field, field_modifier(template['Global Effect +']))
		end
		unless template['Global Effect -'].blank?
			effect_field = template['Global Effect -'].strip.to_sym
			event.add_global_effect!(effect_field, (0 - field_modifier(template['Global Effect -'])))
		end

		unless template['Resource x 3'].blank?
			trade_good = TradeGood.where(name: template['Resource x 3'].strip).first
			if trade_good
				event.add_resource_cost!(trade_good, 3 * EventTypes.random_multiplier)
			end
		end
		unless template['Resource x 2'].blank?
			trade_good = TradeGood.where(name: template['Resource x 2'].strip).first
			if trade_good
				event.add_resource_cost!(trade_good, 2 * EventTypes.random_multiplier)
			end
		end
		unless template['Resource x 1'].blank?
			trade_good = TradeGood.where(name: template['Resource x 1'].strip).first
			if trade_good
				event.add_resource_cost!(trade_good, EventTypes.random_multiplier)
			end
		end

		unless template['Skills x 3'].blank?
			skill = Skill.where(name: template['Skills x 3'].strip).first
			if skill
				event.add_skill_cost!(skill, 3 * EventTypes.random_multiplier)
			end
		end
		unless template['Skills x 2'].blank?
			skill = Skill.where(name: template['Skills x 2'].strip).first
			if skill
				event.add_skill_cost!(skill, 2 * EventTypes.random_multiplier)
			end
		end
		unless template['Skills x 1'].blank?
			skill = Skill.where(name: template['Skills x 1'].strip).first
			if skill
				event.add_skill_cost!(skill, EventTypes.random_multiplier)
			end
		end

		unless template['Rewards'].blank?
			equipment_type = EquipmentType.where(name: template['Rewards'].strip).first
			unless equipment_type
				trade_good = TradeGood.where(name: template['Rewards'].strip).first
				if trade_good
					event.add_trade_goods_reward!(trade_good, EventTypes.random_multiplier)
				end
			else
				event.add_equipment_reward!(equipment_type)
			end
		end

		event.add_credit_reward!(template['Reward Credits'].to_i * EventTypes.random_multiplier) unless template['Reward Credits'].blank?
	end

	def self.field_modifier(field)
		SPECIAL_MODIFIERS.keys.include?(field) ? SPECIAL_MODIFIERS[field] : 5
	end

	def self.random_multiplier
		1 + rand(Global.singleton.citizens)
	end
end

app/models/event.rb
class Event < ActiveRecord::Base
	include EventTypes

	EVENT_TYPES = %w(Crisis Opportunity)

	validates :name, presence: true
	validates :name, length: {in: 3..255 }
	validates :event_type, inclusion: {in: EVENT_TYPES}
	# t.integer :started_on
	# t.integer :finished_on
	validates :max_duration, numericality: {only_integer: true }
	# t.boolean :current
	# t.boolean :success
	# t.text :summary
	# t.text :description
	# t.string :icon
	belongs_to :trigger_after_event, class_name: 'Event'
	belongs_to :winning_project, class_name: 'Project'

	EVENT_TYPES.each do |event_type|
    	define_method("#{event_type.downcase}?") do
  			event_type?(event_type)
	  	end
	  	scope "#{event_type.downcase.pluralize}".to_sym, -> { where(event_type: event_type)}
    end

	has_many :district_effects, dependent: :destroy
	has_many :global_effects, dependent: :destroy
	has_many :event_resource_costs, dependent: :delete_all
	has_many :event_rewards, dependent: :delete_all
	has_many :event_skill_costs, dependent: :delete_all
	has_many :projects, dependent: :destroy
	has_one :previous_event, foreign_key: 'trigger_after_event_id', class_name: 'Event'

	scope :current, -> { where(current: true )}

	acts_as_commontable

	def self.current_opportunity
		@@current_opportunity ||= Event.where(event_type: 'Opportunity', current: true).first
	end

	def self.current_crisis
		@@current_crisis ||= Event.where(event_type: 'Crisis', current: true).first
	end

	def event_type_enum
		EVENT_TYPES
	end

	def event_type?(event_type)
    	self.event_type == event_type
    end

    def chain_next_event!
    	self.trigger_after_event && self.trigger_after_event.update_attributes!(active: true, started_on: Global.singleton.turn)
    end

    def cancel_projects_except_winning!
    	projects.each do |project|
    		unless self.winning_project_id == project.id 
    			project.destroy
    		end
    	end
    end

    def resolved!(project)
    	transaction do
	    	self.winning_project = project 
	    	self.current = false 
	    	self.success = true 
	    	if opportunity?
	    		districts = []
	    		district_effects.each do |effect|
	    			effect.apply!
	    			districts << effect.district
	    		end
	    		global_effects.each do |effect|
	    			effect.apply!
	    		end
	    		districts.uniq!
	    		districts.each do |district|
	    			district.add_report!(self.description)
	    		end
	    	end
	    	self.finished_on = Global.singleton.turn 
	    	save!
	    	chain_next_event! if opportunity?
	    	cancel_projects_except_winning!
	    end
    end

    def expired!
    	transaction do
	    	self.current = false
	    	self.success = false
	    	if crisis?
	    		districts = []
	    		district_effects.each do |effect|
	    			effect.apply!
	    			districts << effect.district
	    		end
	    		global_effects.each do |effect|
	    			effect.apply!
	    		end
	    		districts.uniq!
	    		districts.each do |district|
	    			puts "#{self.description}"
	    			district.add_report!(self.description)
	    		end
	    	end
	    	self.finished_on = Global.singleton.turn 
	    	save!
	    	chain_next_event! if crisis?
	    	cancel_projects_except_winning!
	    end
    end
	
	def add_district_effect!(district, field, value)
		district_effects.create!(:district => district, field => value, :name => "#{self.name} Effect")
	end

	def add_global_effect!(field, value)
		global_effects.create!(field => value, :name => "#{self.name} Effect")
	end

	def add_resource_cost!(trade_good, cost)
		event_resource_costs.create!(trade_good: trade_good, cost: cost)
	end

	def add_skill_cost!(skill, cost)
		event_skill_costs.create!(skill: skill, cost: cost)
	end

	def add_trade_goods_reward!(trade_good, quantity)
		event_rewards.create!(trade_good: trade_good, quantity: quantity)
	end

	def add_equipment_reward!(equipment_type)
		event_rewards.create!(equipment_type: equipment_type, quantity: 1)
	end

	def add_facility_reward!(facility_type)
		event_rewards.create!(facility_type: facility_type, quantity: 1)
	end

	def add_credit_reward!(quantity)
		event_rewards.create!(credits: true, quantity: quantity)
	end

	def suitable_projects(citizen)
		Project.for_event(self).not_for_citizen(citizen).started
	end

	def to_s
		name 
	end

	def expires_on
		if max_duration > 0
			started_on + max_duration
		else
			-1
		end
	end

	def expires?
		Global.singleton.turn == expires_on
	end

	def turn_update!
		expired! if expires?
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show]
  load_and_authorize_resource

  # GET /events/1
  # GET /events/1.json
  def show
    if current_user && current_citizen
      @breadcrumbs = [["Home", root_url], [current_citizen.to_s,"/citizens/#{current_citizen.id}?tab=projects"], [@event.to_s, "/events/#{@event.id}"]]
    end
    @commentable = @event
  end

 private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end
end

app/views/events/_briefing.html.erb
<blockquote>
  <p class="summary"><%=event.summary.html_safe %></p>
  <small><cite title="Source Title">City Core Government</cite></small>
</blockquote>

<%=render partial: '/events/table', locals: {event: event} %>

<% unless defined?(no_button) && no_button %>
	<% if current_citizen %>
		<% if current_citizen.dealing_with_event?(event) %>
		<div class="row">
			<div class="col-lg-offset-6 col-lg-6 text-right">
				<%=link_to "View Projects", "#{current_citizen_path('projects')}", class: 'btn-lg btn-info' %>
			</div>
		</div>
		<% else %>
		<%
			if event.crisis?
				button_label = "Deal with Crisis"
			elsif event.opportunity?
				button_label = "Seize the Opportunity"
			end
		%>
		<div class="row">
			<div class="col-lg-offset-6 col-lg-6 text-right">
				<%=link_to button_label, "#{new_project_path}?event_type=#{event.event_type}", class: 'btn-lg btn-primary' %>
			</div>
		</div>
		<% end %>
	<% end %>
<% end %>

app/views/events/_table.html.erb
<% cache(cache_key_for_model(event)) do %>
	<table class="table table-striped table-hover">
	<tbody>
		<tr>
			<th>Skills</th>
			<td>
				<% event.event_skill_costs.each do |skill_cost| %>
				<%=link_to(skill_cost.skill.name, skill_cost.skill)%> <span class="badge"><%=skill_cost.cost%></span>
				<br/>
				<% end %>
			</td>
		</tr>
		<tr>
			<th>Resources</th>
			<td>
				<% event.event_resource_costs.each do |resource_cost| %>
					<%=link_to(resource_cost.trade_good.name, resource_cost.trade_good)%> <span class="badge"><%=resource_cost.cost%></span>
					<br/>
				<% end %>
			</td>
		</tr>
		<tr>
			<th>Rewards</th>
			<td>
				<% event.event_rewards.each do |reward| %>
					<%=reward.to_s.html_safe%>
					<br/>
				<% end %>
			</td>
		</tr>
		<tr>
			<th>Effects *</th>
			<td>
				<% (event.district_effects.to_a + event.global_effects.to_a).each do |effect| %>
				<%=effect%>
				<br/>
				<% end %>
			</td>
		</tr>
		<% if event.current %>
		<tr>
			<th>Expires</th>
			<td>
				<%=format_turn(event.expires_on)%>
			</td>
		</tr>
		<% else %>
		<tr>
			<th>Finished</th>
			<td>
				<%=format_turn(event.finished_on)%>
			</td>
		</tr>
		<% end %>
		<% if event.winning_project %>
		<tr>
			<th>Resolved By</th>
			<td>
				<%=link_to(event.winning_project.leader.to_s, event.winning_project.leader) %>
			</td>
		</tr>
		<% end %>
	</tbody>
	</table>
	<p class="text-muted">*
		<% if event.crisis? %>
		If the crisis is not successfully resolved
		<% elsif event.opportunity? %>
		If the opportunity is seized
		<% end %>
	</p>

<% end %>

app/views/events/show.html.erb
<% content_for :title, "#{@event.event_type}: #{@event.name}" %>
<% content_for :lead, "#{@event.summary.html_safe}".html_safe %>

<%=render partial: '/events/table', locals: {event: @event} %>

<% content_for :help_title, "What is a #{@event.event_type}?" %>
<% content_for :help_body do %>
The nature of life is that unforeseen events will cross the path of mortals. Some bring opportunities to be seized. Others test our souls. If we are found worthy or wanting, the collective well-being of Ultimapolis is changed for good or for ill. In trying times, great citizens are called to lead the efforts to deal with each <%=@event.event_type.downcase%>.
<% end %>