config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Commontator::Engine => '/vox-populi'
  
  resources :citizens, except: [:index]
  
  resources :projects, except: [:index, :show]
  resources :project_members, only: [:create, :destroy]
  resources :facilities, except: [:index]
  resources :loans, except: [:index, :edit, :update, :show]
  resources :bonds, except: [:index, :edit, :update, :show]
  
  resources :districts, only: [:index, :show]

  resources :equipment_types, only: [:index, :show]
  
  resources :facility_types, only: [:index, :show]
  
  resources :professions, only: [:index, :show]
  
  resources :skills, only: [:index, :show]
  
  resources :trade_goods, only: [:index, :show]
  
  resources :help_topics, only: [:index, :show]
  
  resources :events, only: [:show]

  resources :exchange_equipments, only: [:new, :create]
  resources :exchange_trade_goods, only: [:new, :create]
  
  resources :petitions do 
    member do 
      post :vote_for
      post :vote_against
    end
  end

  resources :stories, only: [:index]
  resources :story_nodes, only: [:show, :edit, :update] do 
    member do 
      get :flag, as: :flag
      get :unflag, as: :unflag
    end
  end
  resources :story_choices, only: [:show, :create]
  
  devise_for :users

  get 'charts/total_land', to: 'district_charts#total_land'
  get 'charts/free_land', to: 'district_charts#free_land'
  get 'charts/transport_capacity', to: 'district_charts#transport_capacity'
  get 'charts/civilians', to: 'district_charts#civilians'
  get 'charts/automatons', to: 'district_charts#automatons'
  get 'charts/unrest', to: 'district_charts#unrest'
  get 'charts/health', to: 'district_charts#health'
  get 'charts/policing', to: 'district_charts#policing'
  get 'charts/social', to: 'district_charts#social'
  get 'charts/environment', to: 'district_charts#environment'
  get 'charts/housing', to: 'district_charts#housing'
  get 'charts/education', to: 'district_charts#education'
  get 'charts/community', to: 'district_charts#community'
  get 'charts/creativity', to: 'district_charts#creativity'
  get 'charts/aesthetics', to: 'district_charts#aesthetics'
  get 'charts/crime', to: 'district_charts#crime'
  get 'charts/corruption', to: 'district_charts#corruption'
  get 'charts/infrastructure', to: 'global_charts#infrastructure'
  get 'charts/grid', to: 'global_charts#grid'
  get 'charts/power', to: 'global_charts#power'
  get 'charts/stability', to: 'global_charts#stability'
  get 'charts/climate', to: 'global_charts#climate'
  get 'charts/liberty', to: 'global_charts#liberty'
  get 'charts/security', to: 'global_charts#security'
  get 'charts/borders', to: 'global_charts#borders'
  get 'charts/inflation', to: 'global_charts#inflation'
  get 'charts/citizens', to: 'global_charts#citizens'
  get 'charts/gdp', to: 'global_charts#gdp'
  get 'charts', to: 'global_charts#index'

  root 'welcome#index'

  get 'test_exception_notifier', :controller => 'application', :action => 'test_exception_notifier'
end

app/models/project.rb
class Project < ActiveRecord::Base

	PROJECT_STATUS = %w(Started Finished)

	belongs_to :leader, class_name: 'Citizen'
	belongs_to :event 
	validates :status, inclusion: {in: PROJECT_STATUS}
	validates :wages, numericality: {only_integer: true}
	# t.integer :began_on
	# t.integer :finished_on

	PROJECT_STATUS.each do |project_status|
    	define_method("#{project_status.downcase}?") do
  			project_status?(project_status)
	  	end
	  	scope "#{project_status.downcase}".to_sym, -> { where(status: project_status)}
    end

    validate :validate_project

	has_many :project_members, dependent: :destroy
	has_many :project_resources, dependent: :delete_all
	has_many :project_skill_points, dependent: :delete_all

	before_save :set_began_on
	after_create :add_leader_as_member!
	after_create :add_resources!
	before_save :wage_change_membership_adjustment!
	after_destroy :return_resources!
	after_create :add_create_report!
	after_destroy :add_cancel_report!

	scope :for_citizen, ->(citizen) { where(["leader_id = ? OR id IN (?)",citizen.id, [0] + ProjectMember.for_citizen(citizen).map{|pm| pm.project_id}]) }	
	scope :for_event, ->(event) { where(event_id: event.id ) }
	scope :not_for_citizen, ->(citizen) { where(["leader_id <> ? AND id NOT IN (?)",citizen.id, [0] + ProjectMember.for_citizen(citizen).map{|pm| pm.project_id}]) }	
	
	default_scope ->{ order('began_on ASC') }

	attr_accessor :skip_resource_costs

	def progress
		return @progress if defined?(@progress)
		@progress = 0
		total = 0
		event_skill_costs.each do |skill_cost|
			if skill_cost.cost > 0
    			@progress = skill_points(skill_cost.skill)
    			total = skill_cost.cost
    		end
    	end
    	return (@progress = 100) unless total > 0
    	@progress = ((@progress.to_f / total.to_f) * 100).round(0).to_i
	end

	def status_enum
		PROJECT_STATUS
	end

	def has_member?(citizen)
		project_members.where(citizen_id: citizen.id).count > 0
	end

	def project_status?(project_status)
    	self.status == project_status
    end

    def event_resource_costs
    	@event_resource_costs ||= self.event && self.event.event_resource_costs
    end

    def event_skill_costs
    	@event_skill_costs ||= self.event && self.event.event_skill_costs
    end

    def event_rewards
    	@event_rewards ||= self.event && self.event.event_rewards
    end

    def resource_mapping(trade_good)
    	return unless trade_good
    	ProjectResource.for_project(self).for_trade_good(trade_good).first
    end

    def skill_mapping(skill)
    	return unless skill
    	ProjectSkillPoint.for_project(self).for_skill(skill).first
    end

    def resource_count(trade_good)
    	mapping = resource_mapping(trade_good)
    	mapping ? mapping.quantity : 0
    end

    def skill_points(skill)
    	mapping = skill_mapping(skill)
    	mapping ? mapping.points : 0
    end

    def has_resources?
    	return true unless event_resource_costs
    	event_resource_costs.each do |resource_cost|
    		return false unless resource_count(resource_cost.trade_good) >= resource_cost.cost
    	end
    	true
    end

    def has_skill_points?
    	return true unless event_skill_costs
    	event_skill_costs.each do |skill_cost|
    		return false unless skill_points(skill_cost.skill) >= skill_cost.cost
    	end
    	true
    end

    def completable?
    	has_resources? && has_skill_points?
    end

    def add_resource!(trade_good, quantity, free_cost=false)
    	return unless trade_good && quantity && self.leader.trade_good_count(trade_good) >= quantity
    	transaction do
    		mapping = resource_mapping(trade_good)
    		if mapping 
    			mapping.quantity += quantity
    			mapping.save!
    		else
    			project_resources.create!(trade_good: trade_good, quantity: quantity)
    		end
    		self.leader.remove_trade_good!(trade_good, quantity) unless free_cost
    	end
    end

    def add_skills!
    	transaction do
	    	event_skill_costs.each do |skill_cost|
	    		skill_mapping = skill_mapping(skill_cost.skill)
	    		skill_mapping ||= project_skill_points.create!(skill: skill_cost.skill, points: 0)
	    		if skill_cost.cost >= skill_mapping.points # work to be done in this skill
			    	project_members.each do |member|
			    		if (skill_rank = member.citizen.skill_rank(skill_cost.skill)) > 0 # member can contribute
			    			if member.sabotaging
			    				skill_mapping.points -= skill_rank
			    			elsif self.leader.credits >= (skill_rank * self.wages) # leader can afford to pay
			    				# pay wages
			    				member_wages = (skill_rank * self.wages)
			    				self.leader.remove_credits!(member_wages, "Pay Wages for #{self}", member.citizen)
			    				member.citizen.add_credits!(member_wages, "Wages for #{self}", self.leader)
			    				# contribute
			    				skill_mapping.points += skill_rank
			    			end
			    		end
			    	end
			    	skill_mapping.save!
			    end
		    end
		end
    end

    def complete!
    	return unless completable?
    	transaction do
	    	self.status = 'Finished'
	    	event_rewards.each do |event_reward|
	    		if event_reward.trade_good && event_reward.quantity > 0
	    			self.leader.add_trade_good!(event_reward.trade_good, event_reward.quantity)
	    		end
	    		if event_reward.equipment_type && event_reward.quantity > 0
	    			self.leader.add_equipment!(event_reward.equipment_type, event_reward.quantity)
	    		end
	    		if event_reward.facility_type && event_reward.quantity > 0
	    			event_reward.quantity.times do
	    				Facility.create_new!(self.leader, event_reward.facility_type, true)
	    			end
	    		end
	    		if event_reward.credits && event_reward.quantity > 0
	    			self.leader.add_credits!(event_reward.quantity, "Winning #{self}")
	    		end
	    	end
	    	self.leader.save!
	    	project_members.each do |member|
				member.citizen.add_report!("Project #{self} was completed")
			end
	    	self.event.resolve!(self)
	    end
    end

	def to_s
		return unless event
		if event.crisis?
			"Crisis: #{event}"
		elsif event.opportunity?
			"Opportunity: #{event}"
		end
	end

	def validate_project
		if new_record?
			unless self.leader 
				errors.add(:leader, "not set")
				return
			end
			if self.leader.on_a_project?
				errors.add(:leader, "already on a project")
				return
			end
			unless skip_resource_costs
				has_resources = true
		    	event_resource_costs.each do |resource_cost|
		    		unless self.leader.trade_good_count(resource_cost.trade_good) >= resource_cost.cost
		    			has_resources = false 
		    			break
		    		end
		    	end
		    	unless has_resources
		    		errors.add(:leader, "doesn't have resources to start project")
		    	end
		    end
		end
	end

	def set_began_on
		self.began_on ||= Global.singleton.turn
	end

	def add_leader_as_member!
		project_members.create!(citizen: leader)
	end

	def wage_change_membership_adjustment!
		if wages_changed?
			self.leader.add_report!("Changed wages on #{self} to #{wages}")
		end
		if wages_changed? && wages_was && wages < wages_was
			project_members.each do |member|
				unless member.citizen_id == leader.id
					member.citizen.add_report!("Project #{self} lowered wages")
					member.destroy
				end
			end
		end
	end

	def add_resources!
		unless skip_resource_costs
			event_resource_costs.each do |resource_cost|
				add_resource!(resource_cost.trade_good, resource_cost.cost)
	    	end
	    else
	    	event_resource_costs.each do |resource_cost|
				add_resource!(resource_cost.trade_good, resource_cost.cost, true)
	    	end
	    end
	end

	def return_resources!
		unless finished?
			transaction do
				project_resources.each do |resource|
					self.leader.add_trade_good!(resource.trade_good, resource.quantity)
				end
			end
		end
	end

	def add_create_report!
		self.leader.add_report!("Started project #{self}")
	end

	def add_cancel_report!
		project_members.each do |member|
			member.citizen.add_report!("Project #{self} was cancelled")
		end
	end

	def turn_update!
		unless finished?
			add_skills!
			complete!
		end
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:edit, :update, :destroy]
  before_action :set_event, only: [:new, :create]
  load_and_authorize_resource

  # GET /projects/new
  def new
    if current_citizen.on_a_project?
      redirect_to "/citizens/#{current_citizen.id}?tab=projects", alert: "You're already involved in a project"
    end
    @project = Project.new(event_id: @event.id)
  end

  # GET /projects/1/edit
  def edit
    @breadcrumbs = [["Home", root_url], [current_citizen.to_s,"/citizens/#{current_citizen.id}?tab=projects"], [@project.to_s, "/projects/#{@project.id}/edit"]]
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.leader = current_citizen

    respond_to do |format|
      if @project.save
        format.html { redirect_to "/citizens/#{current_citizen.id}?tab=projects", notice: 'Project was started.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to "/citizens/#{current_citizen.id}?tab=projects", notice: 'Project was updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to "/citizens/#{current_citizen.id}?tab=projects", notice: 'Project was cancelled.' }
      format.json { head :no_content }
    end
  end

  private
    def set_event
      if params[:event_type].blank?
        redirect_to "/citizens/#{current_citizen.id}?tab=projects", alert: "Invalid event"
        return false
      else
        case params[:event_type]
        when 'Crisis'
          @event = Event.current_crisis
        when 'Opportunity'
          @event = Event.current_opportunity
       end
      end
      unless @event 
        redirect_to "/citizens/#{current_citizen.id}?tab=projects", alert: "Invalid event"
        return false
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:leader_id, :event_id, :began_on, :finished_on, :status, :wages)
    end
end

app/views/projects/_form.html.erb
<%= form_for(@project, html: {class: "form-horizontal"}) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation" class="alert alert-dismissible alert-warning">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <h4><%= pluralize(@project.errors.count, "error") %> prohibited this project from being <%=@project.new_record? ? "started" : "updated"%>:</h4>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%=f.hidden_field :event_id %>
  <%=hidden_field_tag :event_type, params[:event_type] %>
  <%=content_for :event_details %>
  <fieldset>
    <div class="form-group">
      <label for="wages" class="col-lg-2 control-label">Wages Offered</label>
      <div class="col-lg-10">
        <%=f.number_field :wages, class: "form-control" %>
        <span class="help-block">
          This is the amount of credits you will pay for each skill point contribution. Consider the events requirements and rewards when deciding what to pay.
        </span>
      </div>
    </div>

    <div class="form-group">
      <div class="col-lg-2 text-left">
        <%= link_to 'Cancel', "#{citizen_path(current_citizen)}?tab=projects", class: 'btn-lg btn-default' %>
      </div>

      <div class="col-lg-offset-8 col-lg-2 text-right">
        <%= f.submit class: "btn-lg btn-primary" %>
      </div>
    </div>
  </fieldset>
<% end %>

app/views/projects/_index.html.erb
<h2>Projects</h2>

<% cache(cache_key_for_collection("projects-#{@citizen.id}-#{(current_citizen ? current_citizen.id : 'public')}", @projects)) do %>
  <% if @projects.empty? %>
  <div class="alert alert-dismissible alert-warning">
    <h4>No Projects</h4>
    <% if current_citizen && current_citizen.id == @citizen.id %>
    <p>You should join a project to contribute your skills and earn a wage.</p>
    <% else %>
    <p>This citizen has not joined any projects.</p>
    <% end %>
  </div>

  <div class="row">
    <div class="col-lg-6">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">Current Opportunity</h3>
        </div>
        <div class="panel-body">
          <% if Event.current_opportunity %>
          <%=render partial: '/events/briefing', locals: {event: Event.current_opportunity} %>
          <% else %>
          <p>There is no current opportunity. There will be another along shortly.</p>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-lg-6">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h3 class="panel-title">Current Crisis</h3>
        </div>
        <div class="panel-body">
          <% if Event.current_crisis %>
          <%=render partial: '/events/briefing', locals: {event: Event.current_crisis} %>
          <% else %>
          <p>There is no current crisis. Phew!</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <% else %>

  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Event</th>
        <th>Leader</th>
        <th>Status</th>
        <th>Wages</th>
        <th>Progress</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @projects.each do |project| %>
        <tr>
          <td><%= link_to project.event.name, project.event %></td>
          <td><%= link_to project.leader.to_s, project.leader %></td>
          <td>
            <% if project.started? %>
              Started in <%=format_turn(project.began_on)%>
            <% elsif project.finished? %>
              Finished in <%=format_turn(project.finished_on)%>
            <% end %>
          </td>
          <td><%=format_currency  project.wages %></td>
          <td><%=format_rating project.progress %></td>
          <% if can?(:edit, @citizen) %>
            <% if current_citizen.id == project.leader.id %>
          <td>
            <%= link_to 'Cancel Project', project, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
          </td>
          <td>
            <%= link_to 'Adjust Wages', edit_project_path(project),  class: 'btn btn-primary' %>
          </td>
            <% elsif (@project_member_mapping = current_citizen.project_member_mapping(project)) %>
          <td>
            <%= link_to (@project_member_mapping.sabotaging? ? 'Stop Sabotaging' : 'Leave Project'), @project_member_mapping, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
          </td>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% end %>
<% end %>

app/views/projects/_table.html.erb
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Leader</th>
      <th>Status</th>
      <th>Wages / Skill Point</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% projects.each do |project| %>
      <tr>
        <td><%= link_to project.leader.to_s, project.leader %></td>
        <td><%= project.status %></td>
        <td><%=format_currency  project.wages %></td>
        <td>
            <%= form_for(ProjectMember.new(project: project, sabotaging: true)) do |f| %>
            <%=f.hidden_field :project_id %>
            <%=f.hidden_field :sabotaging %>
            <%=f.submit "Sabotage", class: "btn btn-danger" %>
            <% end %>
        </td>
        <td>
            <%= form_for(ProjectMember.new(project: project)) do |f| %>
            <%=f.hidden_field :project_id %>
            <%=f.submit "Help", class: "btn btn-primary" %>
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/projects/edit.html.erb
<% content_for :title, @project.to_s %>
<% content_for :lead, "You can change what you will offer pay to #{@project.event.crisis? ? 'handle this crisis' : 'tacke this opportunity'} but if you decrease the amount all existing members will leave immediately.".html_safe %>

<h2>Adjust Wages Offered</h2>
<%= render 'form' %>

app/views/projects/new.html.erb
<% content_for :title, @event.name %>
<% content_for(:event_details) do %>
<%=render partial: '/events/briefing', locals: {event: @project.event, no_button: true} %>
<% if @event.event_resource_costs.count > 0 %>
	<p>You need to have the following resources to start this project. They will be taken out of your inventory and only returned if you cancel the project before it completes.</p>
	<ul class="list-group">
		<% @event.event_resource_costs.each do |resource_cost| %>
		<li class="list-group-item">
			<%=link_to resource_cost.trade_good.to_s, resource_cost.trade_good, target: '_new' %>
			<span class="badge"><%=resource_cost.cost%></span>
		</li>
		<% end %>
	</ul>
<% end %>
<% end %>
<% projects = current_citizen ? @event.suitable_projects(current_citizen) : [] %>
<% if projects.empty? %>
<% content_for :lead, "You can organise a project to #{@event.crisis? ? 'handle this crisis' : 'tacke this opportunity'} but you will need to offer wages for other citizens to assist you. Furthermore, you will be responsible for providing all the resources required to tackle the project. If you should succeed all the rewards are yours alone.".html_safe %>
<% else %>
<% content_for :lead, "There are existing projects attempting to #{@event.crisis? ? 'handle this crisis' : 'tacke this opportunity'} but you can start your own and offer better wages for other citizens to assist you instead. As you will be responsible for providing all the resources required to tackle the project, you will reap all the rewards for yourself.".html_safe %>
<h2>Existing Projects</h2>
<%=render partial: '/projects/table', locals: {projects:  projects } %>
<% end %>
<h2>New Project</h2>
<%= render 'form' %>